package io.appthreat.ruby2atom.parsing

import io.appthreat.ruby2atom.testfixtures.RubyCode2CpgFixture
import io.shiftleft.codepropertygraph.Cpg
import io.shiftleft.codepropertygraph.generated.Operators
import io.shiftleft.semanticcpg.language.*

/** Pattern matching lowering (plan 04 §2). Every `case ... in <pattern>` clause used to collapse to
  * `Unknown` (or, for plain array patterns, to bindings of the wrong shape), so destructuring
  * produced no bindings at all. The lowering now destructures patterns into assignments of the
  * match variables against the matched value's parts.
  *
  * Fixture JSON generated by rbastgen 2.1.0 from `resources/ruby/pattern_matching.rb`.
  */
class PatternMatchingTests extends RubyCode2CpgFixture:

  // `case response ...` lowers the subject into a tmp variable; bindings index into it.
  private def assignmentCode(cpg: Cpg): List[String] =
      cpg.assignment.code.l.distinct.sorted

  "hash patterns destructure to assignments of the match variables" in {
      val cpg   = fixtureWithoutUnknowns("pattern_matching")
      val codes = assignmentCode(cpg)

      // in { status: :ok, data: { user: name } }
      codes should contain("name = <tmp-0>[:data][:user]")
      // in { status: Integer => code, data: String } - the match_as binding
      codes should contain("code = <tmp-0>[:status]")

      cpg.local.name.l should contain("name")
      cpg.local.name.l should contain("code")
      cpg.identifier.name.l should contain("name")
  }

  "array patterns bind elements by position, rest binds the remainder" in {
      val cpg   = fixtureWithoutUnknowns("pattern_matching")
      val codes = assignmentCode(cpg)

      // in [first, *rest]
      codes should contain("first = <tmp-0>[0]")
      codes should contain("rest = <tmp-0>[1]")

      cpg.local.name.l should contain("first")
      cpg.local.name.l should contain("rest")
  }

  "find patterns bind their element to the matched value (position is not static)" in {
      val cpg = fixtureWithoutUnknowns("pattern_matching")
      // in [*, middle, *]
      assignmentCode(cpg) should contain("middle = <tmp-0>")
      cpg.local.name.l should contain("middle")
  }

  "guards join the pattern condition" in {
      val cpg = fixtureWithoutUnknowns("pattern_matching")
      // in { status: Integer => code, data: String } if code < 400
      cpg.call.nameExact(Operators.lessThan).l should not be empty
      cpg.call.nameExact(Operators.logicalAnd).l should not be empty
      // unless_guard negates its condition; this fixture has none, so no extra not-call.
      cpg.call.nameExact(Operators.not).l shouldBe empty
  }

  "match alternatives join their conditions with a logical or" in {
      val cpg = fixtureWithoutUnknowns("pattern_matching")
      // in Integer | String
      cpg.call.nameExact(Operators.logicalOr).l should not be empty
      cpg.call.nameExact(Operators.equals).l should not be empty
  }

  "pin patterns become equality conditions against the pinned value" in {
      val cpg = fixtureWithoutUnknowns("pattern_matching")
      // in { status: ^expected } - the pin compares the matched value with `expected` and binds
      // nothing itself.
      cpg.call.nameExact(Operators.equals).argument.isIdentifier.name.l should contain("expected")
      cpg.call.nameExact(Operators.equals).argument.isIdentifier.name.l should contain("<tmp-0>")
  }

  "rightward assignment `value => other` binds the pattern variable" in {
      val cpg = fixtureWithoutUnknowns("pattern_matching")
      assignmentCode(cpg) should contain("other = value")
      cpg.local.name.l should contain("other")
  }

  "one-line `config in { name: }` binds the shorthand variable without the colon" in {
      val cpg = fixtureWithoutUnknowns("pattern_matching")
      assignmentCode(cpg) should contain("name = config[:name]")
      cpg.local.name.l should contain("name")
      cpg.local.name.l should not contain "name:"
  }

  "literal-only patterns produce a match condition and no bindings" in {
      val cpg = fixtureWithoutUnknowns("pattern_matching")
      // `case response` makes each clause a conditional over the subject tmp; the :ok literal
      // clause matches via === without binding anything.
      cpg.call.nameExact(Operators.equals).argument.isIdentifier.name.l should contain("<tmp-0>")
      cpg.local.name.l.toSet should not contain "ok"
  }
end PatternMatchingTests
