{% set version = "2.0.11" %}

package:
  name: chen
  version: {{ version }}
about:
  home: https://github.com/appthreat/chen
  license: Apache-2.0
  license_file: LICENSE
  summary: "Code Hierarchy Exploration Net (chen)"
  dev_url: https://github.com/appthreat/chen
requirements:
  build:
    - python
    - pip
  host:
    - pip
    - python
    - setuptools
    - poetry
  run:
    - python>=3.10,<3.12
    - conda-forge::httpx>=0.27.0
    - conda-forge::websockets>=12.0
    - conda-forge::orjson>=3.10.1,<4.0.0
    - conda-forge::rich>=13.7.1,<14.0.0
    - conda-forge::oras-py==0.1.26
    - conda-forge::appdirs>=1.4.4,<2.0.0
    - conda-forge::psutil>=5.9.8,<6.0.0
    - conda-forge::packageurl-python>=0.11.2,<0.12.0
    - conda-forge::gitpython>=3.1.43,<4.0.0
    - conda-forge::networkx>=3.3
    - conda-forge::numpy>=1.26
    - conda-forge::scipy>=1.11.3
build:
  pin_depends: record
  noarch: python
  script: |
    cp ${RECIPE_DIR}/pyproject.toml ${SRC_DIR}/
    cp ${RECIPE_DIR}/LICENSE ${SRC_DIR}/
    cp ${RECIPE_DIR}/README.md ${SRC_DIR}/
    cp ${RECIPE_DIR}/docker-compose.yml ${SRC_DIR}/
    cp -rf ${RECIPE_DIR}/docs ${SRC_DIR}/
    cp -rf ${RECIPE_DIR}/notebooks ${SRC_DIR}/
    rm -rf ${SRC_DIR}/{ci,console,dataflowengineoss,macros,platform,project,scripts,semanticcpg,target,tests,workspace}
    {{ PYTHON }} -m pip install --no-build-isolation --no-deps --ignore-installed .
  entry_points:
    - chen = chenpy.cli:main

source:
  path: ./chenpy
  folder: chenpy

extra:
  maintainers:
    - Team AppThreat <cloud@appthreat.com>
