#!/usr/bin/env python3
"""Regenerate the identifier character classes of pythonGrammar.jj from CPython itself.

Usage (run with the newest CPython whose identifiers the grammar should accept):

    python3.15 scripts/gen_identifier_classes.py pythonGrammar.jj

CPython's tokenizer accepts an identifier when its first character is XID_Start or '_' and
every further character is XID_Continue (``_PyUnicode_ScanIdentifier``), using its own
``unicodedata`` (Unicode 17.0.0 in 3.15); the parser then NFKC-normalises it. ``str.isidentifier``
applies exactly that check, so it is the oracle used here. The grammar lexes UTF-16 code units,
so only the Basic Multilingual Plane is emitted.

The script rewrites the block between the BEGIN/END GENERATED IDENTIFIER CLASSES markers in
place and leaves the rest of the grammar untouched.
"""
import sys
import unicodedata

BEGIN = "// BEGIN GENERATED IDENTIFIER CLASSES"
END = "// END GENERATED IDENTIFIER CLASSES"


def ranges(predicate):
    out, start, prev = [], None, None
    for cp in range(0x10000):
        if 0xD800 <= cp <= 0xDFFF or not predicate(cp):
            if start is not None:
                out.append((start, prev))
                start = None
            continue
        if start is None:
            start = cp
        prev = cp
    if start is not None:
        out.append((start, prev))
    return out


def describe(lo, hi):
    cats = sorted({unicodedata.category(chr(c)) for c in range(lo, hi + 1)})
    cat = "/".join(cats) if len(cats) <= 3 else "/".join(cats[:3]) + "/.."
    first = unicodedata.name(chr(lo), f"U+{lo:04X}")
    if lo == hi:
        return f"{cat:<8} {first}"
    last = unicodedata.name(chr(hi), f"U+{hi:04X}")
    return f"{cat:<8} [{hi - lo + 1}] {first}..{last}"


def klass(name, rs):
    """`| <#NAME: item // comment` followed by one `| item` line per further range."""
    head = f"| <#{name}: "
    pad = " " * (len(head) - 2)
    lines = []
    for i, (lo, hi) in enumerate(rs):
        item = f'"\\u{lo:04X}"' if lo == hi else f'["\\u{lo:04X}" - "\\u{hi:04X}"]'
        lead = head if i == 0 else pad + "| "
        lines.append(f"{lead}{item} // {describe(lo, hi)}")
    lines.append(pad + ">")
    return lines


def main():
    path = sys.argv[1]
    is_start = lambda c: chr(c) == "_" or chr(c).isidentifier()
    is_continue = lambda c: ("a" + chr(c)).isidentifier()
    start = ranges(is_start)
    # ID_CONTINUE is emitted as <ID_START> | <ID_CONTINUE_ONLY> to keep the table compact.
    cont_only = ranges(lambda c: is_continue(c) and not is_start(c))
    version = sys.version.split()[0]
    body = [
        BEGIN,
        f"// Generated by scripts/gen_identifier_classes.py with CPython {version}",
        f"// (unicodedata {unicodedata.unidata_version}): ID_START = XID_Start | '_',",
        "// ID_CONTINUE = XID_Continue, Basic Multilingual Plane only. Do not edit by hand.",
        "TOKEN: {",
        "  <NAME: <ID_START> (<ID_CONTINUE>)*>",
        *klass("ID_START", start),
        *klass("ID_CONTINUE_ONLY", cont_only),
        "| <#ID_CONTINUE: <ID_START> | <ID_CONTINUE_ONLY> >",
        "}",
        END,
    ]
    src = open(path, encoding="utf-8").read()
    if BEGIN not in src or END not in src:
        raise SystemExit(f"markers not found in {path}")
    head, rest = src.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(head + "\n".join(body) + tail)
    print(f"{path}: ID_START {len(start)} ranges, ID_CONTINUE_ONLY {len(cont_only)} ranges "
          f"(CPython {version}, Unicode {unicodedata.unidata_version})")


if __name__ == "__main__":
    main()
