#!/bin/sh
# Generates the predefined macro tables c2cpg falls back to when a translation unit's compiler
# cannot be run (src/main/resources/predefined-macros/*.txt).
#
# Each table lists the macros a real compiler predefines for one target, for C and for C++, in
# the format of the EDG C/C++ front end's predefined_macros.txt (see its make_predef_macro_table):
#
#   mode[,mode]   cannot_redefine   name   value
#
# where the modes are gnu/gcc/gpp for GCC (both languages/C/C++), clang/clang_c/clang_cpp for
# Clang, and microsoft/microsoft_c/microsoft_cpp for MSVC.
#
# GCC runs in Docker (the official gcc image, one run per platform). Clang is the LLVM clang on
# the PATH (or $CLANG), asked for each target with --target. The MSVC tables are what clang
# predefines in MSVC compatibility mode (as clang-cl does), without clang's own identity macros:
# MSVC's cl.exe has no option that lists its predefined macros.
#
# Usage: tools/predefined-macros/generate.sh [output-dir]

set -eu

OUT=${1:-"$(cd "$(dirname "$0")/../.." && pwd)/src/main/resources/predefined-macros"}
CLANG=${CLANG:-clang}
GCC_IMAGE=${GCC_IMAGE:-gcc:14}
MSVC_VERSION=${MSVC_VERSION:-19.40}
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
mkdir -p "$OUT"

# merge <c-macros> <cpp-macros> <both-mode> <c-mode> <cpp-mode>: one table body on stdout
merge() {
  awk -v both="$3" -v cmode="$4" -v cppmode="$5" '
    function parse(line,   rest, name, value, i) {
      rest = substr(line, 9)
      if (match(rest, /^[A-Za-z_][A-Za-z0-9_]*\([^)]*\)/)) { name = substr(rest, 1, RLENGTH) }
      else { match(rest, /^[A-Za-z_][A-Za-z0-9_]*/); name = substr(rest, 1, RLENGTH) }
      value = substr(rest, length(name) + 1); sub(/^ /, "", value)
      PNAME = name; PVALUE = value
    }
    FNR == NR { if ($0 ~ /^#define /) { parse($0); c[PNAME] = PVALUE } ; next }
    { if ($0 ~ /^#define /) { parse($0); cpp[PNAME] = PVALUE } }
    END {
      for (n in c) {
        if ((n in cpp) && cpp[n] == c[n]) print both " no  " n " " c[n]
        else print cmode " no  " n " " c[n]
      }
      for (n in cpp) if (!(n in c) || cpp[n] != c[n]) print cppmode " no  " n " " cpp[n]
    }' "$1" "$2" | LC_ALL=C sort -k3,3 -k1,1
}

# header <file> <description> <c-command> <cpp-command> <version text>
header() {
  {
    echo "# Predefined macros of $2."
    echo "#"
    echo "# Format (as the EDG C/C++ front end's predefined_macros.txt):"
    echo "#   mode[,mode]   cannot_redefine   name   value"
    echo "#"
    echo "# Generated by tools/predefined-macros/generate.sh on $(date -u +%Y-%m-%d)."
    echo "# C:   $3"
    echo "# C++: $4"
    echo "#"
    printf '%s\n' "$5" | sed 's/^/# /'
    echo "#"
  } >"$1"
}

gcc_table() { # gcc_table <name> <docker-platform>
  run="docker run --rm -i --platform $2 $GCC_IMAGE"
  $run gcc -x c -dM -E - </dev/null >"$TMP/c"
  $run g++ -x c++ -dM -E - </dev/null >"$TMP/cpp"
  version=$($run gcc --version | head -1)
  header "$OUT/$1.txt" "GCC on $2" "gcc -x c -dM -E -" "g++ -x c++ -dM -E -" "$version ($GCC_IMAGE)"
  merge "$TMP/c" "$TMP/cpp" gnu gcc gpp >>"$OUT/$1.txt"
}

clang_table() { # clang_table <name> <target>
  "$CLANG" --target="$2" -x c -dM -E - </dev/null >"$TMP/c"
  "$CLANG" --target="$2" -x c++ -dM -E - </dev/null >"$TMP/cpp"
  version=$("$CLANG" --version | head -1)
  header "$OUT/$1.txt" "Clang for $2" "clang --target=$2 -x c -dM -E -" \
    "clang --target=$2 -x c++ -dM -E -" "$version"
  merge "$TMP/c" "$TMP/cpp" clang clang_c clang_cpp >>"$OUT/$1.txt"
}

msvc_table() { # msvc_table <name> <target>
  opts="--target=$2 -fms-extensions -fms-compatibility -fms-compatibility-version=$MSVC_VERSION"
  # clang's own identity, which cl.exe does not predefine
  strip='^#define (__clang|__llvm__|__GNUC|__GXX|__VERSION__|__STDC_HOSTED__|__OBJC|__BLOCKS__)'
  "$CLANG" $opts -x c -dM -E - </dev/null | grep -Ev "$strip" >"$TMP/c"
  "$CLANG" $opts -x c++ -dM -E - </dev/null | grep -Ev "$strip" >"$TMP/cpp"
  version=$("$CLANG" --version | head -1)
  header "$OUT/$1.txt" "MSVC $MSVC_VERSION for $2, as clang predefines them in MSVC compatibility mode" \
    "clang $opts -x c -dM -E -" "clang $opts -x c++ -dM -E -" "$version"
  merge "$TMP/c" "$TMP/cpp" microsoft microsoft_c microsoft_cpp >>"$OUT/$1.txt"
}

gcc_table gcc-linux-x86_64 linux/amd64
gcc_table gcc-linux-aarch64 linux/arm64
clang_table clang-linux-x86_64 x86_64-unknown-linux-gnu
clang_table clang-linux-aarch64 aarch64-unknown-linux-gnu
clang_table clang-macos-arm64 arm64-apple-macosx
clang_table clang-macos-x86_64 x86_64-apple-macosx
msvc_table msvc-windows-x64 x86_64-pc-windows-msvc
msvc_table msvc-windows-arm64 aarch64-pc-windows-msvc
