#!/usr/bin/env python3
"""Generates src/main/resources/builtin-functions.txt, the signatures of the GCC and Clang builtin
functions c2cpg gives the calls the parser does not know (`__builtin___memcpy_chk`).

The signatures come from the EDG C/C++ front end's src/builtin_defs.h (Apache-2.0 WITH
LLVM-exception, https://edgcpp.org/LICENSE.txt), which EDG generates from GCC's and Clang's own
builtin definitions. Target-specific builtins (vector, SIMD and per-architecture ones) and
type-generic ones (the __atomic and __sync families) are left out. Where GCC and Clang declare a
builtin differently, GCC's declaration is kept. The C library's FORTIFY functions (__memcpy_chk) are
listed with the signatures of the compiler builtins they match (__builtin___memcpy_chk).

Usage: tools/builtins/generate.py <path to the EDG source tree> [output file]
"""
import os
import re
import sys

TARGET_MARKERS = (
    "_ia32_", "_neon_", "_sve_", "_sme_", "_riscv", "_arm_", "_aarch64_", "_mve_", "_altivec",
    "_vsx", "_mips", "_s390", "_nvptx", "_amdgcn", "_wasm", "_hexagon", "_loongarch", "_bpf",
    "_ve_", "_ppc", "_spe_", "_msa_", "_lasx", "_lsx", "_cheri", "_HEXAGON", "_xcore", "_csky",
    "_tile", "_sparc", "_kvx", "_r600", "_si_", "_mma_", "_vec_", "_crypto_", "_darn",
)

# EDG's names for target-dependent types, spelled as the parser spells them on an LP64 target
EDG_TYPES = {
    "__edg_size_type__": "unsigned long int",
    "__edg_ptrdiff_type__": "long int",
    "__edg_bool_type__": "bool",
    "__edg_wchar_type__": "wchar_t",
}

BASIC = [
    (r"\bunsigned long long\b(?! int)", "unsigned long long int"),
    (r"\blong long\b(?! int)", "long long int"),
    (r"\bunsigned long\b(?! (?:int|long))", "unsigned long int"),
    (r"\bunsigned short\b(?! int)", "unsigned short int"),
    (r"(?<!unsigned )(?<!long )\blong\b(?! (?:int|long|double))", "long int"),
    (r"(?<!unsigned )\bshort\b(?! int)", "short int"),
    (r"\bunsigned\b(?! (?:int|long|short|char))", "unsigned int"),
]


def spell(t):
    t = t.strip()
    for k, v in EDG_TYPES.items():
        t = t.replace(k, v)
    t = re.sub(r"\b(const|volatile|restrict|__restrict)\b", "", t)
    for pattern, repl in BASIC:
        t = re.sub(pattern, repl, t)
    t = re.sub(r"\s+", " ", t).strip()
    return t.replace(" *", "*").replace("* ", "*")


def split_params(params):
    out, depth, cur = [], 0, ""
    for ch in params:
        if ch == "," and depth == 0:
            out.append(cur)
            cur = ""
            continue
        depth += ch == "("
        depth -= ch == ")"
        cur += ch
    if cur.strip():
        out.append(cur)
    return out


def main():
    edg = sys.argv[1]
    out = sys.argv[2] if len(sys.argv) > 2 else os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "..", "..", "src", "main", "resources",
        "builtin-functions.txt")
    text = open(os.path.join(edg, "src", "builtin_defs.h"), encoding="utf-8").read()
    types = dict(re.findall(r'/\* (bfti_[0-9a-f]+) \*/ "([^"]*)"', text))
    conditions = dict(re.findall(r'/\* (bfci_[0-9a-f]+) \*/ "([^"]*)"', text))
    chosen = {}
    for name, cond, tidx in re.findall(r'\{ "([^"]+)", (bfci_[0-9a-f]+), (bfti_[0-9a-f]+), bfk_', text):
        if not name.startswith(("__builtin_", "__sync_", "__atomic_")):
            continue
        if any(m in name for m in TARGET_MARKERS):
            continue
        sig = types.get(tidx, "")
        if not sig or "vector_type" in sig or "__builtin_" in sig.split("(")[0] or "__edg_" in sig.replace(
                "__edg_throw__", "").replace("__edg_size_type__", "").replace(
                "__edg_ptrdiff_type__", "").replace("__edg_bool_type__", "").replace(
                "__edg_wchar_type__", ""):
            continue
        sig = sig.replace("__edg_throw__()", "").strip()
        # a type-generic builtin (the __atomic and __sync families) has no one signature
        if re.fullmatch(r"void\s*\(\.\.\.\)", sig):
            continue
        m = re.match(r"^(.*?)\s*\((.*)\)\s*$", sig)
        if not m:
            continue
        ret, params = m.group(1), m.group(2)
        gcc = "g" in conditions.get(cond, "")
        if name in chosen and not (gcc and not chosen[name][2]):
            continue
        plist = [spell(p) for p in split_params(params)]
        if plist == ["void"]:
            plist = []
        chosen[name] = (spell(ret), plist, gcc)
    # the C library's FORTIFY functions (__memcpy_chk) are declared as the compiler's builtins are
    for name in list(chosen):
        if name.startswith("__builtin___") and name.endswith("_chk"):
            chosen.setdefault(name[len("__builtin_"):], chosen[name])
    with open(out, "w", encoding="utf-8") as f:
        f.write("# Signatures of the GCC and Clang builtin functions: name;return type;parameter types.\n")
        f.write("# Generated by tools/builtins/generate.py from the EDG C/C++ front end's src/builtin_defs.h\n")
        f.write("# (Apache-2.0 WITH LLVM-exception, https://edgcpp.org/LICENSE.txt), which EDG generates from\n")
        f.write("# GCC's and Clang's builtin definitions. Target-specific and type-generic builtins are left\n")
        f.write("# out; the C library's FORTIFY functions (__memcpy_chk) are listed with their builtins' signatures.\n")
        for name in sorted(chosen):
            ret, plist, _ = chosen[name]
            f.write(f"{name};{ret};{','.join(plist)}\n")
    print(f"{len(chosen)} builtins written to {out}")


if __name__ == "__main__":
    main()
