package io.appthreat.c2cpg.parser

import io.appthreat.c2cpg.Config
import io.appthreat.c2cpg.utils.IncludeAutoDiscovery

import java.nio.charset.StandardCharsets
import java.nio.file.{Files, Path, Paths}
import scala.collection.mutable
import scala.jdk.CollectionConverters.*
import scala.util.Try

/** A lexical pre-pass over a C/C++ tree that finds the build-configuration macros hiding code from
  * the parser. A project built by `configure`, CMake, Meson or Kconfig gets names such as
  * `CONFIG_WAV_DEMUXER` or `HAVE_O_CLOEXEC` from a generated header the checkout does not contain;
  * without it every `#if CONFIG_X` evaluates to 0 and the parser never sees the code it gates.
  *
  * The census reads every `#if`/`#ifdef`/`#ifndef`/`#elif` in the tree and keeps the macros that
  * nothing defines: not the tree, not the include paths, not the system headers. For each one it
  * counts the lines that defining it to 1 would make visible, less the lines it would hide. It
  * never looks inside a condition it cannot read as a single macro test (`#if A && B`, `#if X >=
  * 2`): those count as `mixed` uses and gain nothing.
  *
  * Each external macro gets one tier:
  *   - [[Tier.Auto]]: strong evidence it is a build option. A configure/CMake/Meson template in the
  *     tree declares it (`config.h.in`, `#cmakedefine`, `#mesondefine`), or it follows the
  *     build-option naming (`CONFIG_`, `ENABLE_`), and defining it shows more code than it hides.
  *     `--auto-defines` applies these.
  *   - [[Tier.Suggest]]: it shows more code than it hides, but nothing says it is a build option (a
  *     `HAVE_` probe with no template, a debug switch). Reported for a person or agent to choose.
  *   - [[Tier.Skip]]: compiler, platform or dependency macros (`_WIN32`, `__linux__`, `MBEDTLS_...`
  *     when `<mbedtls/...>` is included from outside the tree), system-header names, and anything
  *     that hides as much as it shows. Listed with the reason, never defined.
  */
object MacroCensus:

  enum Tier:
    case Auto, Suggest, Skip

  final case class Entry(
    name: String,
    tier: Tier,
    reason: String,
    evidence: String,
    gainLines: Int,
    positiveUses: Int,
    negativeUses: Int,
    mixedUses: Int,
    files: Int
  )

  final case class Report(entries: List[Entry], scannedFiles: Int):
    def auto: List[Entry]    = entries.filter(_.tier == Tier.Auto)
    def suggest: List[Entry] = entries.filter(_.tier == Tier.Suggest)

    /** the defines `--auto-defines` adds, in `NAME=1` form */
    def autoDefines: Set[String] = auto.map(e => s"${e.name}=1").toSet

    def toJson: String =
      def q(s: String) = "\"" + s.flatMap {
          case '"'  => "\\\""
          case '\\' => "\\\\"
          case c    => c.toString
      } + "\""
      entries
          .map { e =>
              s"""  {"macro": ${q(e.name)}, "tier": ${q(
                    e.tier.toString.toLowerCase
                  )}, "reason": ${q(
                    e.reason
                  )}, "evidence": ${q(e.evidence)}, "gain_lines": ${e.gainLines}, "positive_uses": ${e
                      .positiveUses}, "negative_uses": ${e.negativeUses}, "mixed_uses": ${e
                      .mixedUses}, "files": ${e.files}}"""
          }
          .mkString(s"""{"scanned_files": $scannedFiles, "macros": [\n""", ",\n", "\n]}\n")

    /** a header `--macro-files` accepts: the auto tier active, the suggest tier commented out */
    def toMacroHeader: String =
      val sb = new StringBuilder
      sb.append("/* Generated by the macro census. Review before use.\n")
      sb.append(" * Pass with --macro-files; uncomment a suggestion to enable it. */\n\n")
      auto.foreach(e =>
          sb.append(s"#define ${e.name} 1 /* +${e.gainLines} lines, ${e.evidence} */\n")
      )
      if suggest.nonEmpty then sb.append("\n/* suggestions */\n")
      suggest.foreach(e =>
          sb.append(s"/* #define ${e.name} 1 */ /* +${e.gainLines} lines, ${e.reason} */\n")
      )
      sb.toString

    /** a short human summary: counts and the largest entries of each defined tier */
    def summary(limit: Int = 10): String =
      val sb = new StringBuilder
      sb.append(
        s"Macro census: $scannedFiles files, ${entries.size} undefined condition macros; " +
            s"${auto.size} auto (+${auto.map(_.gainLines).sum} lines), " +
            s"${suggest.size} suggested (+${suggest.map(_.gainLines).sum} lines)\n"
      )
      def rows(title: String, es: List[Entry]) =
          if es.nonEmpty then
            sb.append(s"  $title:\n")
            es.take(limit).foreach(e =>
                sb.append(f"    ${e.name}%-44s +${e.gainLines}%-6d ${e.evidence}\n")
            )
            if es.size > limit then sb.append(s"    ... ${es.size - limit} more\n")
      rows("auto", auto)
      rows("suggested", suggest)
      sb.toString
  end Report

  private val SourceExtensions =
      Set(".c", ".cc", ".cpp", ".cxx", ".c++", ".h", ".hh", ".hpp", ".hxx", ".inc", ".ipp", ".tcc")
  private val TemplateSuffixes = Seq(".h.in", ".h.cmake", ".hin", ".h.meson", ".hpp.in")
  private val SkippedDirs      = Set(".git", ".hg", ".svn", ".chen", "node_modules")

  /** Names a compiler, platform or ABI owns. `_` prefixes are reserved to the implementation; the
    * words are the OS, architecture and toolchain vocabulary every portable project tests.
    */
  private val PlatformPattern =
      ("^_|WIN32|WIN64|WINDOWS|WINAPI|WINSOCK|MINGW|CYGWIN|APPLE|MACOS|DARWIN|ANDROID|LINUX|" +
          "FREEBSD|NETBSD|OPENBSD|SOLARIS|SUNOS|HAIKU|FUCHSIA|EMSCRIPTEN|WASM|AIX|HPUX|X86|AMD64|" +
          "I386|AARCH64|ARM|MIPS|POWERPC|PPC|RISCV|SPARC|S390|LOONG|IA64|MSVC|MSC_|GNUC|CLANG|" +
          "ENDIAN|NDEBUG|STDC|POSIX|XOPEN|GNU_SOURCE|cplusplus").r

  private val ErrnoPattern = "E[A-Z0-9]{2,15}".r

  /** Configure-style names that gate optional code in the project itself. `HAVE_` is not one: it is
    * a probe of the host, and needs a template to count as a build option.
    */
  private val BuildOptionPrefixes = Seq("CONFIG_", "ENABLE_")

  private val ConditionPattern =
      """^\s*#\s*(if|ifdef|ifndef|elif|else|endif)\b(.*)$""".r
  private val DefinePattern = """^\s*#\s*(?:define|undef)\s+([A-Za-z_]\w*)""".r.unanchored
  // the same, over a whole header's text at once: `^` must match at every line start
  private val HeaderDefinePattern = """(?m)^[ \t]*#[ \t]*define[ \t]+([A-Za-z_]\w*)""".r
  private val TemplatePattern =
      """^\s*#\s*(?:cmakedefine01|cmakedefine|mesondefine|undef|define)\s+([A-Za-z_]\w*)""".r
          .unanchored
  private val IncludePattern = """^\s*#\s*include\s*[<"]([^>"]+)[>"]""".r.unanchored
  private val Identifier     = """[A-Za-z_]\w*""".r
  // a single-macro test: `X`, `!X`, `defined X`, `defined(X)`, `!defined(X)`, parenthesised
  private val SingleTest = """^[\s!(]*(?:defined\s*\(?\s*)?([A-Za-z_]\w*)[\s)]*$""".r

  private val TestPathPattern =
      """(^|/)(tests?|testing|unittests?|benchmarks?)(/|$)|(_test|_unittest|_benchmark|_bench)\.[^/]+$""".r

  /** Run the census over the config's input path. System include paths are read for the names they
    * define whether or not the analysis itself auto-discovers them.
    */
  def run(config: Config): Report =
    val root         = Paths.get(config.inputPath).toAbsolutePath.normalize
    val userDefined  = config.defines.map(_.takeWhile(_ != '='))
    val includeRoots = config.includePaths.map(p => Paths.get(p).toAbsolutePath.normalize)
    val discovery    = config.withIncludePathsAutoDiscovery(true)
    val systemRoots =
        Try(
          IncludeAutoDiscovery.discoverIncludePathsC(discovery) ++
              IncludeAutoDiscovery.discoverIncludePathsCPP(discovery)
        ).getOrElse(Set.empty)
    analyse(root, includeRoots.filterNot(_.startsWith(root)) ++ systemRoots, userDefined)

  /** The census proper, separated from include-path discovery so tests can drive it. */
  def analyse(root: Path, externalRoots: Set[Path], userDefined: Set[String]): Report =
    val treeFiles     = filesUnder(root)
    val sources       = treeFiles.filter(isSource)
    val templates     = treeFiles.filter(isTemplate)
    val treeDefined   = mutable.HashSet.empty[String]
    val templateNames = mutable.HashSet.empty[String]
    val includeTops   = mutable.HashSet.empty[String]
    val stats         = mutable.HashMap.empty[String, Stats]

    templates.foreach(f =>
        logicalLines(f).foreach {
            case TemplatePattern(name) => templateNames += name
            case _                     => ()
        }
    )
    sources.foreach { f =>
      val lines = logicalLines(f)
      lines.foreach {
          case DefinePattern(name) => treeDefined += name
          case _                   => ()
      }
      lines.foreach {
          case IncludePattern(target) if target.contains('/') =>
              includeTops += target.takeWhile(_ != '/').toLowerCase
          case _ => ()
      }
      val rel = root.relativize(f).toString.replace('\\', '/')
      collectConditions(lines, isTest = TestPathPattern.findFirstIn(rel).nonEmpty, stats, rel)
    }
    // a dependency's own top-level include directory: `<mbedtls/ssl.h>` when the tree has no
    // `mbedtls/` of its own
    val treeDirNames = treeFiles.flatMap(f =>
        Option(root.relativize(f).getParent).toList.flatMap(_.iterator().asScala.map(_.toString))
    ).map(_.toLowerCase).toSet
    val dependencyTops  = includeTops.toSet -- treeDirNames
    val candidates      = stats.keySet.toSet -- treeDefined -- userDefined
    val externalDefined = definedIn(externalRoots, candidates)

    val entries = candidates.toList.map { name =>
      val s        = stats(name)
      val template = templateNames.contains(name)
      val evidence =
          if template then "template"
          else if BuildOptionPrefixes.exists(name.startsWith) then "build-option name"
          else "undefined"
      val owner = name.takeWhile(_ != '_').toLowerCase
      val (tier, reason) =
          if PlatformPattern.findFirstIn(name).nonEmpty then (Tier.Skip, "compiler or platform")
          // `#ifdef ENOMEDIUM`: an errno the build host's <errno.h> may lack, never a switch
          else if ErrnoPattern.matches(name) then (Tier.Skip, "errno constant")
          else if externalDefined.contains(name) then (Tier.Skip, "defined by an included header")
          else if dependencyTops.contains(owner) then
            (Tier.Skip, s"owned by the <$owner/...> dependency")
          else if s.gain <= 0 then (Tier.Skip, "shows no more code than it hides")
          else if evidence != "undefined" then (Tier.Auto, evidence)
          else (Tier.Suggest, "no build-option evidence")
      Entry(
        name = name,
        tier = tier,
        reason = reason,
        evidence = evidence,
        s.gain,
        s.positive,
        s.negative,
        s.mixed,
        s.files.size
      )
    }
    Report(
      entries.sortBy(e => (e.tier.ordinal, -e.gainLines, e.name)),
      sources.size
    )
  end analyse

  private final class Stats:
    var gain     = 0
    var positive = 0
    var negative = 0
    var mixed    = 0
    val files    = mutable.HashSet.empty[String]

  private final class Open(val condition: String, val kind: String, val start: Int):
    val cuts                       = mutable.ArrayBuffer(start)
    var hasElif                    = false
    val names: mutable.Set[String] = mutable.LinkedHashSet.empty

  private def collectConditions(
    lines: IndexedSeq[String],
    isTest: Boolean,
    stats: mutable.HashMap[String, Stats],
    file: String
  ): Unit =
    val stack = mutable.Stack.empty[Open]
    lines.indices.foreach { n =>
        lines(n) match
          case ConditionPattern(kind, rest) =>
              val cond = rest.trim
              kind match
                case "if" | "ifdef" | "ifndef" =>
                    val o = new Open(cond, kind, n)
                    o.names ++= conditionNames(cond)
                    stack.push(o)
                case "elif" if stack.nonEmpty =>
                    stack.top.cuts += n
                    stack.top.hasElif = true
                    stack.top.names ++= conditionNames(cond)
                case "else" if stack.nonEmpty => stack.top.cuts += n
                case "endif" if stack.nonEmpty =>
                    val o = stack.pop()
                    o.cuts += n
                    val spans = o.cuts.sliding(2).map(w => w(1) - w(0) - 1).toList
                    val single =
                        if o.hasElif then None
                        else
                          o.kind match
                            case "ifdef" | "ifndef" => Identifier.findFirstIn(o.condition)
                            case _ =>
                                o.condition match
                                  case SingleTest(name) if name != "defined" => Some(name)
                                  case _                                     => None
                    o.names.foreach { name =>
                      val s = stats.getOrElseUpdate(name, new Stats)
                      s.files += file
                      single.filter(_ == name) match
                        case Some(_) =>
                            val negated = o.kind == "ifndef" ||
                                (o.kind == "if" && o.condition.count(_ == '!') % 2 == 1)
                            val shown   = spans.headOption.getOrElse(0)
                            val other   = spans.drop(1).sum
                            if negated then s.negative += 1 else s.positive += 1
                            // test code is not what the analysis is for: it neither earns
                            // nor costs a macro its gain
                            if !isTest then
                              s.gain += (if negated then other - shown else shown - other)
                        case None => s.mixed += 1
                    }
                case _ => ()
              end match
          case _ => ()
    }
  end collectConditions

  private def conditionNames(cond: String): List[String] =
      Identifier.findAllIn(stripComments(cond)).filterNot(_ == "defined").toList.distinct

  private def stripComments(s: String): String =
      s.replaceAll("""/\*.*?\*/""", " ").replaceAll("//.*$", "")

  private def isSource(p: Path): Boolean =
    val n = p.getFileName.toString.toLowerCase
    SourceExtensions.exists(n.endsWith) && !TemplateSuffixes.exists(n.endsWith)

  private def isTemplate(p: Path): Boolean =
    val n = p.getFileName.toString.toLowerCase
    TemplateSuffixes.exists(n.endsWith) || n == "config.h.in"

  private def filesUnder(root: Path): List[Path] =
      if !Files.isDirectory(root) then Nil
      else
        Try {
            val s = Files.walk(root)
            try
                s.iterator()
                    .asScala
                    .filter(p =>
                        Files.isRegularFile(p) &&
                            !root.relativize(p).iterator().asScala.exists(c =>
                                SkippedDirs.contains(c.toString)
                            )
                    )
                    .toList
            finally s.close()
        }.getOrElse(Nil)

  /** Every name `#define`d in the headers under these roots, restricted to the candidates so the
    * set stays small. System headers are read as bytes: they are not always UTF-8.
    */
  private def definedIn(roots: Set[Path], candidates: Set[String]): Set[String] =
      if candidates.isEmpty then Set.empty
      else
        val found = mutable.HashSet.empty[String]
        roots.foreach(r =>
            filesUnder(r).foreach { f =>
                Try(new String(Files.readAllBytes(f), StandardCharsets.ISO_8859_1)).foreach(text =>
                    HeaderDefinePattern.findAllMatchIn(text).foreach { m =>
                      val name = m.group(1)
                      if candidates.contains(name) then found += name
                    }
                )
            }
        )
        found.toSet

  /** The file's logical lines: backslash continuations joined, block comments blanked, line numbers
    * kept (a joined or blanked line leaves an empty line in its place).
    */
  private def logicalLines(f: Path): IndexedSeq[String] =
    val raw = Try(new String(Files.readAllBytes(f), StandardCharsets.ISO_8859_1)).getOrElse("")
    val out = mutable.ArrayBuffer.empty[String]
    val cur = new StringBuilder
    var inComment = false
    var pending   = 0
    raw.split("\n", -1).foreach { line0 =>
      val line = line0.stripSuffix("\r")
      val sb   = new StringBuilder
      var i    = 0
      while i < line.length do
        if inComment then
          val end = line.indexOf("*/", i)
          if end < 0 then i = line.length
          else
            inComment = false
            i = end + 2
        else if line.startsWith("/*", i) then
          inComment = true
          i += 2
        else if line.startsWith("//", i) then i = line.length
        else
          sb.append(line.charAt(i))
          i += 1
      val text = sb.toString
      if text.endsWith("\\") && !inComment then
        cur.append(text.dropRight(1)).append(' ')
        pending += 1
      else
        cur.append(text)
        out += cur.toString
        (0 until pending).foreach(_ => out += "")
        cur.clear()
        pending = 0
    }
    if cur.nonEmpty then out += cur.toString
    out.toIndexedSeq
  end logicalLines
end MacroCensus
