{% set version = "0.0.19" %}

package:
  name: chen
  version: {{ version }}
about:
  home: https://github.com/appthreat/chen
  license: Apache-2.0
  summary: "Code Hierarchy Exploration Net (chen)"
  dev_url: https://github.com/appthreat/chen
dependencies:
  - python>=3.8.1,<3.12
  - conda-forge::httpx>=0.24.1,<0.25.0
  - conda-forge::websockets>=11.0.2,<12.0.0
  - conda-forge::orjson>=3.9.0,<4.0.0
  - conda-forge::rich>=13.4.1,<14.0.0
  - conda-forge::oras>=0.1.24,<0.2.0
  - conda-forge::appdirs>=1.4.4,<2.0.0
  - conda-forge::psutil>=5.9.5,<6.0.0
  - conda-forge::packageurl-python>=0.11.2,<0.12.0
  - conda-forge::gitpython>=3.1.37,<4.0.0

requirements:
  host:
    - python
    - pip
  run:
    - python

build:
  script: poetry build
  noarch: python

source:
  path: ..
