package io.appthreat.x2cpg.utils

import scala.io.Source

/** The UTS #39 skeleton of a string: two identifiers with the same skeleton look alike (`раypal`
  * with a Cyrillic `р` and `а`, and `paypal`). skeleton(X) = NFD(map(NFD(X))), where `map` replaces
  * each code point by its prototype from Unicode's confusables data (resource
  * `unicode/confusables.txt`, generated by `tools/unicode/generate-confusables.py`).
  */
object UnicodeSkeleton:

  private lazy val prototypes: Map[Int, String] =
    val stream = Option(getClass.getResourceAsStream("/unicode/confusables.txt"))
    stream.map { s =>
        try
            Source.fromInputStream(s, "UTF-8").getLines()
                .filterNot(l => l.startsWith("#") || l.isBlank)
                .flatMap { line =>
                    line.split('\t') match
                      case Array(source, target) =>
                          scala.util.Try {
                              val from = Integer.parseInt(source.trim, 16)
                              val to   = target.trim.split(' ').map(h => Integer.parseInt(h, 16))
                              from -> new String(to, 0, to.length)
                          }.toOption
                      case _ => None
                }.toMap
        finally s.close()
    }.getOrElse(Map.empty)

  // java.text.Normalizer, looked up at run time: the compiler cannot read some java.text class
  // files of recent JDKs
  private lazy val nfd: String => String =
    val normalizer = Class.forName("java.text.Normalizer")
    val form       = Class.forName("java.text.Normalizer$Form")
    val nfdForm    = form.getField("NFD").get(null)
    val normalize  = normalizer.getMethod("normalize", classOf[CharSequence], form)
    (s: String) => normalize.invoke(null, s, nfdForm).asInstanceOf[String]

  def skeleton(s: String): String =
    val decomposed = nfd(s)
    val mapped     = new java.lang.StringBuilder
    decomposed.codePoints().forEach(cp =>
        prototypes.get(cp) match
          case Some(p) => mapped.append(p)
          case None    => mapped.appendCodePoint(cp)
    )
    nfd(mapped.toString)

  def isAscii(s: String): Boolean = s.forall(_ < 128)

  /** The bidirectional formatting characters a Trojan Source attack (CVE-2021-42574) hides code
    * with: the embeddings, overrides and isolates, and their terminators.
    */
  val BidiControls: Set[Int] =
      Set(0x202a, 0x202b, 0x202c, 0x202d, 0x202e, 0x2066, 0x2067, 0x2068, 0x2069)

  /** The bidi controls in `s`, as `U+XXXX`, in order of first appearance. */
  def bidiControlsIn(s: String): List[String] =
      s.codePoints().toArray.toList.filter(BidiControls.contains).distinct.map(cp =>
          f"U+$cp%04X"
      )
end UnicodeSkeleton
