{% set version = "0.0.19" %}

package:
  name: chen
  version: {{ version }}
about:
  home: https://github.com/appthreat/chen
  license: Apache-2.0
  license_file: LICENSE
  summary: "Code Hierarchy Exploration Net (chen)"
  dev_url: https://github.com/appthreat/chen
dependencies:
  - python>=3.8.1,<3.12
  - conda-forge::httpx>=0.24.1,<0.25.0
  - conda-forge::websockets>=11.0.2,<12.0.0
  - conda-forge::orjson>=3.9.0,<4.0.0
  - conda-forge::rich>=13.4.1,<14.0.0
  - conda-forge::oras-py>=0.1.25
  - conda-forge::appdirs>=1.4.4,<2.0.0
  - conda-forge::psutil>=5.9.5,<6.0.0
  - conda-forge::packageurl-python>=0.11.2,<0.12.0
  - conda-forge::gitpython>=3.1.37,<4.0.0
  - conda-forge::networkx>=3.1
  - conda-forge::numpy>=1.26
  - conda-forge::scipy>=1.11.3
requirements:
  build:
    - python
    - pip
  host:
    - pip
    - python
    - setuptools
    - poetry
  run:
    - python
    - httpx
    - websockets
    - orjson
    - rich
    - oras-py
    - appdirs
    - psutil
    - packageurl-python
    - gitpython
    - networkx
    - numpy
    - scipy

build:
  noarch: python
  script: |
    cp ${RECIPE_DIR}/../pyproject.toml ${SRC_DIR}/
    cp ${RECIPE_DIR}/../LICENSE ${SRC_DIR}/
    cp ${RECIPE_DIR}/../README.md ${SRC_DIR}/
    cp ${RECIPE_DIR}/../docker-compose.yml ${SRC_DIR}/
    cp -rf ${RECIPE_DIR}/../docs ${SRC_DIR}/
    cp -rf ${RECIPE_DIR}/../notebooks ${SRC_DIR}/
    {{ PYTHON }} -m pip install --no-build-isolation --no-deps --ignore-installed .
  entry_points:
    - chen = chenpy.cli:main

source:
  path: .
  folder: chenpy

outputs:
  - name: chen
    files:
      - chenpy
      - docs
      - notebooks
      - README.md
      - LICENSE
      - docker-compose.yml

extra:
  maintainers:
    - Team AppThreat <cloud@appthreat.com>
