#!/usr/bin/env python3
"""Generate the confusables resource the Unicode source-integrity tags read.

Downloads UTS #39's confusables.txt for a pinned Unicode version and writes
src/main/resources/unicode/confusables.txt: one mapping per line,
`<source code point>\t<prototype code points>` in hexadecimal, after a header
naming the version. The Unicode licence notice is written beside it.

  generate-confusables.py [--version 18.0.0]
"""

import argparse
import re
import sys
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
RESOURCES = HERE.parent.parent / "src" / "main" / "resources" / "unicode"
URL = "https://www.unicode.org/Public/{version}/security/confusables.txt"
LICENSE_URL = "https://www.unicode.org/license.txt"


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--version", default="18.0.0")
    args = ap.parse_args()
    text = urllib.request.urlopen(URL.format(version=args.version), timeout=60).read().decode("utf-8")
    header = re.search(r"^# Version: (\S+)", text, re.M)
    if not header or header.group(1) != args.version:
        sys.exit(f"expected confusables for Unicode {args.version}")
    rows = []
    for line in text.splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        fields = [f.strip() for f in line.split(";")]
        if len(fields) < 2:
            continue
        rows.append(f"{fields[0].lower()}\t{fields[1].lower()}")
    RESOURCES.mkdir(parents=True, exist_ok=True)
    out = RESOURCES / "confusables.txt"
    out.write_text(
        f"# Unicode {args.version} confusables (UTS #39), generated by "
        "tools/unicode/generate-confusables.py\n"
        f"# Source: {URL.format(version=args.version)}\n"
        "# Copyright Unicode, Inc. Licensed under the Unicode License v3: see LICENSE-UNICODE.txt\n"
        + "\n".join(rows)
        + "\n",
        encoding="utf-8",
    )
    licence = urllib.request.urlopen(LICENSE_URL, timeout=60).read().decode("utf-8")
    (RESOURCES / "LICENSE-UNICODE.txt").write_text(licence, encoding="utf-8")
    print(f"{len(rows)} mappings written to {out}")


if __name__ == "__main__":
    main()
