# CHEN-EXPECT: no-parse-errors
# CHEN-EXPECT: node-absent UNKNOWN
# Identifiers per CPython 3.15's lexical rules: XID_Start/'_' then XID_Continue from Unicode
# 17.0.0, NFKC-normalised. Generated by tools/gen_unicode_corpus.py - do not edit by hand.
Ᲊᲊ = 0  # U+1C89/U+1C8A CYRILLIC CAPITAL/SMALL LETTER TJE (Unicode 16.0) [U+1C89 U+1C8A]
xꟋꟍ = 1  # U+A7CB/U+A7CD Latin rams horn, s with diagonal stroke (Unicode 16.0) [U+A7CB U+A7CD]
࢏_noon = 2  # U+088F ARABIC LETTER NOON WITH RING ABOVE (Unicode 17.0) [U+088F]
౜_shrii = 3  # U+0C5C TELUGU ARCHAIC SHRII (Unicode 17.0) [U+0C5C]
೜_shrii = 4  # U+0CDC KANNADA ARCHAIC SHRII (Unicode 17.0) [U+0CDC]
x꟱ = 5  # U+A7F1 MODIFIER LETTER CAPITAL S (Unicode 17.0) [U+A7F1]
café = 6  # e + U+0301 COMBINING ACUTE ACCENT (decomposed 'cafe') [U+0301]
नमस्ते = 7  # Devanagari namaste: virama U+094D, vowel sign U+0947 [U+0928 U+092E U+0938 U+094D U+0924 U+0947]
வணக்கம் = 8  # Tamil vanakkam: pulli U+0BCD [U+0BB5 U+0BA3 U+0B95 U+0BCD U+0B95 U+0BAE U+0BCD]
สวัสดี = 9  # Thai sawasdee: U+0E31, U+0E35 vowel marks [U+0E2A U+0E27 U+0E31 U+0E2A U+0E14 U+0E35]
নমস্কার = 10  # Bengali nomoskar: U+09CD virama, U+09BE sign [U+09A8 U+09AE U+09B8 U+09CD U+0995 U+09BE U+09B0]
తెలుగు = 11  # Telugu: U+0C46, U+0C41 vowel signs (Mn/Mc) [U+0C24 U+0C46 U+0C32 U+0C41 U+0C17 U+0C41]
שָׁלוֹם = 12  # Hebrew with niqqud points (Mn) [U+05E9 U+05B8 U+05C1 U+05DC U+05D5 U+05B9 U+05DD]
مُحَمَّد = 13  # Arabic with harakat (Mn) [U+0645 U+064F U+062D U+064E U+0645 U+0651 U+064E U+062F]
x⃗ = 14  # U+20D7 COMBINING RIGHT ARROW ABOVE (vector notation) [U+20D7]
l·l = 15  # U+00B7 MIDDLE DOT (Catalan l.l) [U+00B7]
a·b = 16  # U+0387 GREEK ANO TELEIA (NFKC -> U+00B7) [U+0387]
ア・イ = 17  # U+30FB KATAKANA MIDDLE DOT (Other_ID_Continue since Unicode 15.1) [U+30A2 U+30FB U+30A4]
ｱ･ｲ = 18  # U+FF65 HALFWIDTH KATAKANA MIDDLE DOT [U+FF71 U+FF65 U+FF72]
x‿y = 19  # U+203F UNDERTIE (Pc) [U+203F]
x⁀y = 20  # U+2040 CHARACTER TIE (Pc) [U+2040]
x＿y = 21  # U+FF3F FULLWIDTH LOW LINE (Pc) [U+FF3F]
می‌خواهم = 22  # Persian with U+200C ZERO WIDTH NON-JOINER [U+0645 U+06CC U+200C U+062E U+0648 U+0627 U+0647 U+0645]
x‍y = 23  # U+200D ZERO WIDTH JOINER [U+200D]
عدد١٢ = 24  # Arabic-Indic digits U+0661 U+0662 [U+0639 U+062F U+062F U+0661 U+0662]
x१२ = 25  # Devanagari digits U+0967 U+0968 [U+0967 U+0968]
x１ = 26  # U+FF11 FULLWIDTH DIGIT ONE [U+FF11]
x፩ = 27  # U+1369 ETHIOPIC DIGIT ONE (No, Other_ID_Continue) [U+1369]
变量 = 28  # CJK [U+53D8 U+91CF]
한글 = 29  # Hangul syllables [U+D55C U+AE00]
αβγ = 30  # Greek [U+03B1 U+03B2 U+03B3]
переменная = 31  # Cyrillic [U+043F U+0435 U+0440 U+0435 U+043C U+0435 U+043D U+043D U+0430 U+044F]
total = Ᲊᲊ + xꟋꟍ + ࢏_noon + ౜_shrii + ೜_shrii + x꟱ + café + नमस्ते + வணக்கம் + สวัสดี + নমস্কার + తెలుగు + שָׁלוֹם + مُحَمَّد + x⃗ + l·l + a·b + ア・イ + ｱ･ｲ + x‿y + x⁀y + x＿y + می‌خواهم + x‍y + عدد١٢ + x१२ + x１ + x፩ + 变量 + 한글 + αβγ + переменная

# NFKC-equivalent spellings bind the same name (CPython normalises identifiers).
ﬁle_count = 1  # U+FB01 LATIN SMALL LIGATURE FI
assert file_count == 1
ｘｙ = 1  # FULLWIDTH LATIN SMALL LETTER X/Y
assert xy == 1
Ⅰ_numeral = 1  # U+2160 ROMAN NUMERAL ONE
assert I_numeral == 1

def функция(аргумент, café=1):
    return аргумент + café

class क्लास:  # Devanagari 'class' with virama and vowel sign
    गुण = 1

print(функция(1), क्लास.गुण)
