name: master
on:
  workflow_dispatch:    # allow to manually trigger this workflow
  push:
    branches: [main, "release/*"]
    tags: ["*"]
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
permissions: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up JDK
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961  # v5.7.0
        with:
          distribution: 'temurin'
          java-version: '25'
      - uses: sbt/setup-sbt@bfea3c5f48abd221b04a6df4798aa5eb8b6a2baf  # v1.5.6
      - name: "Install PHP"
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240  # 2.37.2
        with:
          coverage: "none"
          php-version: "8.4"
          tools: composer:v2
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version: '3.12'
      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020  # v7.0.0
        with:
          node-version: '25.x'
          package-manager-cache: false
      - uses: oras-project/setup-oras@1d808f7d7f6995cc68b7bf507bfe5c5446e1dc9d  # v2.0.1
      - name: Delete `.rustup` directory
        run: rm -rf /home/runner/.rustup # to save disk space
        if: runner.os == 'Linux'
      - name: Delete `.cargo` directory # to save disk space
        run: rm -rf /home/runner/.cargo
        if: runner.os == 'Linux'
      - name: Install graphviz-dev
        run: sudo apt install -y graphviz-dev
        if: runner.os == 'Linux'
      - name: Install graphviz-dev
        run: |
          brew install sbt
        if: runner.os == 'macOS'
      - name: Install and test
        run: |
          bash ./platform/frontends/php2atom/install.sh
          npm install -g @appthreat/atom-parsetools
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9  # v6.1.0
        with:
          path: |
            ~/.sbt
            ~/.coursier
          key: ${{ runner.os }}-sbt-${{ hashfiles('**/build.sbt') }}
          lookup-only: true
      - run: sbt scalafmtCheck +test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF-8"
        if: runner.os != 'Windows'
      - name: Compile and run tests
        run: sbt scalafmtCheck +test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF-8"
        if: runner.os == 'Windows'
      - name: Generate SBOM with cdxgen
        run: |
          npm install -g @cyclonedx/cdxgen
          cdxgen -t sbt -o bom.json . -p --no-recurse
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
